<?php
// function comment_buddy_menu() {
//   $items = array();
//   $items['comment_created'] = array(
//     'title' => "Comment Created!",
//     'page callback' => 'create_comment',
//         'access callback' => TRUE,
//         'type' => MENU_CALLBACK,
//     );
//     $items['comment_deleted'] = array(
//       'title' => 'Comment Deleted',
//       'page callback' => 'delete_comment',
//       'access callback' => TRUE,
//       'type' => MENU_CALLBACK,
//     );
//     $items['comment_changed'] = array(
//       'title' => 'Comment Changed',
//       'page callback' => 'change_comment',
//       'access callback' => TRUE,
//       'type' => MENU_CALLBACK,
//     );
//
//     return $items;
//   }

function comment_buddy_comment_insert() {
    drupal_set_message("Thank you! Comment submitted!");
}

function comment_buddy_comment_delete() {
    drupal_set_message("Your comment was deleted!");
}

function comment_buddy_comment_update() {
  drupal_set_message("Your comment was updated!");
}

// function greeting_user_logout() {
//   $_GET['destination'] = 'farewell';
// }
