<?php
function greeting_menu() {
  $items = array();
  $items['hello_friend'] = array(
    'title' => "hello Friend!",
    'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['farwell'] = array(
      'title' => 'Farwell Friend!',
      'page callback' => 'say_farwell',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }

function say_hello() {
    return '<p>Hello my dear friend!</p>';
}

function say_farwell() {
    return '<p>Fare thee well my dear friend!</p>';
}
